<Project>
  <PropertyGroup>
    <Version>3.1.4</Version>
    <AssemblyVersion>3.1.4.0</AssemblyVersion>
    <FileVersion>3.1.4.0</FileVersion>
    <InformationalVersion>3.1.4</InformationalVersion>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <AnalysisLevel>latest</AnalysisLevel>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
