<Project>
  <PropertyGroup>
    <Version>3.3.35</Version>
    <AssemblyVersion>3.3.35.0</AssemblyVersion>
    <FileVersion>3.3.35.0</FileVersion>
    <InformationalVersion>3.3.35</InformationalVersion>
    <Authors>Jetrho Pérez M.</Authors>
    <Company>Jetrho Pérez M.</Company>
    <Copyright>Copyright © 2026 Jetrho Pérez M.</Copyright>
    <Product>JetVenta</Product>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <AnalysisLevel>latest</AnalysisLevel>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
